### ISSUE TITLE
Resolve spancat dependencies in entity_replacer_v1

### ISSUE THREAD

**Issue by SrijithSrinath** [KennethEnevoldsen/augmenty#185]
In the current function ent_augmenter_v1, resolves all dependencies without resolving the dependency on spancat objects.
When we change the entities in the sentence, please help in resolving spancat labels like "sc", "spans" or custom label. The feature will allow running augmenty on a dataset that has both entities and spans. 
For example -

"My name is Srijith Srinath. I work in Spacy."

Ents - 
PERSON_NAME - Srijith Srinath
WORKPLACE - Spacy

Spans - 
PERSON_DESC - My name is Srijith Srinath
WORKPLACE_DESC - I work in Spacy

If we change the ent "Srijith Srianth" to "John Doe". The changes occur only on ents. Make changes to spans as well, as follows -

Ents - 
PERSON_NAME - John Doe
WORKPLACE - Spacy

Spans - 
PERSON_DESC - My name is John Doe
WORKPLACE_DESC - I work in Spacy

**Comment by KennethEnevoldsen** [comment]
Hi, @SrijithSrinath sorry for missing this (feel free to remind me next time). This sounds like a very reasonable addition. I will def. see if I can try to add it in.

**Comment by KennethEnevoldsen** [comment]
Hi @SrijithSrinath I have added the functionality in #201, it will be merged it once the tests have passed.
