### ISSUE TITLE
Back translation augmentation

### ISSUE THREAD

**Issue by martincjespersen** [KennethEnevoldsen/augmenty#26]
Augmenting of a document using back translation of various languages e.g., using huggingface models: https://huggingface.co/models?pipeline_tag=translation. 

Example blog: https://dzlab.github.io/dltips/en/pytorch/text-augmentation/

**Example sentence:**
Augmenty is an augmentation library based on spaCy for augmenting texts. Augmenty differs from other augmentation libraries in that it corrects (as far as possible) the token, sentence and document labels under the augmentation.

**English -> Danish (Google):**
Augmenty er et udvidelsesbibliotek baseret på spaCy til forstørrelse af tekster. Augmenty adskiller sig fra andre augmentationsbiblioteker ved, at den korrigerer (så vidt muligt) token-, sætnings- og dokumentetiketterne under augmentationen.

**Danish -> English (Google):**
Augmenty is an **extension** library based on spaCy for **enlarging** texts. Augmenty differs from other augmentation libraries in that it corrects (as far as possible) the token, sentence, and document labels during augmentation.

**Comment by KennethEnevoldsen** [comment]
This would require solving issue #14 as the model currently takes in one example at a time, which would be unfeasible for back-translation.

**Comment by KennethEnevoldsen** [comment]
I will close this as stale @martincjespersen, let me know if you still would like this change.
