### ISSUE TITLE
I fear the streamlit app is down. 

### ISSUE THREAD

**Issue by koaning** [KennethEnevoldsen/augmenty#42]
I fear the streamlit app, found [here](https://share.streamlit.io/kennethenevoldsen/augmenty/dev/streamlit.py) is down. 

![image](https://user-images.githubusercontent.com/1019791/151932563-50fe0c57-3ea4-414a-9660-fe06179a15e5.png)

**Comment by KennethEnevoldsen** [comment]
Thanks, @koaning for noticing, will take a look at this later this week.

**Comment by KennethEnevoldsen** [comment]
Thanks again @koaning for reporting this issue, the demo is now up back up and running again although I have moved the link to [here](https://share.streamlit.io/kennethenevoldsen/augmenty/demo/streamlit.py).
