### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by sugatoray** [KennethEnevoldsen/augmenty#47]
Please add a license file to the repo and also include the license file in the pypi source.

**Comment by KennethEnevoldsen** [comment]
Version should now have been added in the [latest commit](https://github.com/KennethEnevoldsen/augmenty/commit/658e3ac7141a289e5eb3b047879d5503ee12ee7f).

**Comment by KennethEnevoldsen** [comment]
I have also attached license file in the setup.cfg as well as bumped the version ID to 0.0.13.
