### ISSUE TITLE
Sample fake entities for entity augmenter using Faker package

### ISSUE THREAD

**Issue by martincjespersen** [KennethEnevoldsen/augmenty#81]
Add sampling of entities (such as names or adresses) from https://faker.readthedocs.io/en/master/locales/da_DK.html. This tool supports random sampling of entities for numerous of languages.

**Comment by KennethEnevoldsen** [comment]
Thanks for this suggestion @martincjespersen. Def. a good suggestion.

**Comment by KennethEnevoldsen** [comment]
Added in PR
